### ISSUE TITLE
how to add api key?

### ISSUE THREAD

**Issue by conradkay** [Skitionek/alpha-vantage-graphql-module#3]
i am getting missing alpha vantage api key errors.

**Comment by Skitionek** [comment]
You are right I forgot to document it, you should provide 'AV_KEY' environmental variable (containing your API key).
You can also declare it within the code either by custom module declaration, giving API as a parameter in here: https://github.com/Skitionek/alpha-vantage-graphql-module/blob/master/src/index.js#L21
or by providing right module settings overwrites.
Example:
```js
import { alphaVantageModuleFactory, alphaVantageProviderFactory } from 'alpha-vantage-graphql-module';

export const alphaVantageProvider = alphaVantageProviderFactory(/*YOUR_API_KEY*/);

export const alphaVantageModule = alphaVantageModuleFactory({
	providers: [
		alphaVantageProvider
	]
});
```
